name: Code coverage

on:
  push:
    branches:
      - master
      - devlopment
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: '0 4 * * *' #every day at 5am France
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov  
      uses: ./
      with:
        #commenting out token because tokenless uploads are now supported
        #token: ${{secrets.CODECOV_TOKEN}}
        flags: pytest
        name: codecov-1
